#!/bin/bash

# Get the current directory
current_dir=$(pwd)

# Get the list of directories
directories=$(find $current_dir -type d)

# Get the list of files to copy
files_to_copy="0-isupper.c 0-memset.c 0-strcat.c 1-isdigit.c 1-memcpy.c 1-strncat.c 100-atoi.c 2-strchr.c 2-strlen.c 2-strncpy.c 3-islower.c 3-puts.c 3-strcmp.c 3-strspn.c 4-isalpha.c 4-strpbrk.c 5-strstr.c 6-abs.c 9-strcpy.c _putchar.c"

# Loop through the directories
for directory in $directories; do

  # Get the list of files in the directory
  files=$(find $directory -type f)

  # Loop through the files
  for file in $files; do

    # Check if the file matches the list of files to copy
    if [[ $file == *"$files_to_copy"* ]]; then

      # Copy the file to a new directory
      cp $file libmy.a
    fi
  done
done
